---
- name: Install Docker, Docker Compose and NVM
  hosts: all
  sudo: yes
  roles:
    - franklinkim.docker
    - franklinkim.docker-compose
    - moviedo.nvm
  tasks:
    - name: add user vagrant to the docker group to avoid type sudo for each docker command
      user: name=vagrant
            groups=docker
            append=yes
  vars:
    nvm_version: v0.29.0
    nvm_node_version: v4.2.2
